language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:mapnik/boost
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y libboost1.49-dev
  - sudo apt-get install -y libboost-chrono1.49-dev
  - sudo apt-get install -y libboost-date-time1.49-dev
  - sudo apt-get install -y libboost-filesystem1.49-dev
  - sudo apt-get install -y libboost-program-options1.49-dev
  - sudo apt-get install -y libboost-regex1.49-dev
  - sudo apt-get install -y libboost-system1.49-dev
  - sudo apt-get install -y libboost-thread1.49-dev
  - sudo apt-get install -y libssl-dev
  - sudo apt-get install -y libsqlite3-dev
  - sudo apt-get install -y libdb++-dev
script:
  - ./configure && make && sudo make install
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64
  - /usr/local/share/libcoin/bin/blocktree
  - /usr/local/share/libcoin/bin/claims
  - /usr/local/share/libcoin/bin/client
  - /usr/local/share/libcoin/bin/extended_key
  - /usr/local/share/libcoin/bin/jsonance
  - /usr/local/share/libcoin/bin/merkletrie
  - /usr/local/share/libcoin/bin/namecoin
  - /usr/local/share/libcoin/bin/shamir
  - /usr/local/share/libcoin/bin/sqliterate
  - /usr/local/share/libcoin/bin/serialize
