language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost1.53-all-dev
  - sudo apt-get install -y libssl-dev
  - sudo apt-get install -y libsqlite3-dev
  - sudo apt-get install -y libdb++-dev
script: ./configure && make && sudo make install
